apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: library-system
  labels:
    app: notification-service
    component: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        component: notifications
    spec:
      containers:
      - name: notification-service
        image: ghcr.io/sachinthadaham/library-manager-microservices/notification-service:a93037d65bce3624a12cd78313a9f97e95f6dee0
        imagePullPolicy: Always
        ports:
        - containerPort: 3006
        envFrom:
        - configMapRef:
            name: library-config
        env:
        - name: PORT
          value: "3006"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3006
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3006
          initialDelaySeconds: 20
          periodSeconds: 30
