apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: library-system
  labels:
    app: notification-service
    component: notifications
spec:
  type: ClusterIP
  ports:
  - port: 3006
    targetPort: 3006
    protocol: TCP
  selector:
    app: notification-service
