apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
  namespace: library-system
  labels:
    app: reservation-service
    component: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
        component: reservations
    spec:
      containers:
      - name: reservation-service
        image: ghcr.io/sachinthadaham/library-manager-microservices/reservation-service:d87609cd7c15f4acb72005955b98431d7229b5ea
        imagePullPolicy: Always
        ports:
        - containerPort: 3005
        envFrom:
        - configMapRef:
            name: library-config
        env:
        - name: PORT
          value: "3005"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: library-secrets
              key: JWT_SECRET
        - name: MONGODB_URI
          value: "mongodb+srv://f1admin:DGoSkGXpThvjkv2E@cluster0.gsu8i5s.mongodb.net/library-reservation-db?retryWrites=true&w=majority&appName=Cluster0"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          tcpSocket:
            port: 3005
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3005
          initialDelaySeconds: 20
          periodSeconds: 30




