apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  namespace: library-system
  labels:
    app: book-service
    component: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
        component: catalog
    spec:
      containers:
      - name: book-service
        image: ghcr.io/sachinthadaham/library-manager-microservices/book-service:8d6228081171d3efda67f8a00bb3aeced203b533
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: library-config
        env:
        - name: PORT
          value: "3002"
        - name: MONGODB_URI
          value: "mongodb+srv://f1admin:DGoSkGXpThvjkv2E@cluster0.gsu8i5s.mongodb.net/library-book-db?retryWrites=true&w=majority&appName=Cluster0"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          tcpSocket:
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3002
          initialDelaySeconds: 20
          periodSeconds: 30



