apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: library-system
  labels:
    app: book-service
    component: catalog
spec:
  type: ClusterIP
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
  selector:
    app: book-service
