apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrow-service
  namespace: library-system
  labels:
    app: borrow-service
    component: borrowing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: borrow-service
  template:
    metadata:
      labels:
        app: borrow-service
        component: borrowing
    spec:
      containers:
      - name: borrow-service
        image: ghcr.io/sachinthadaham/library-manager-microservices/borrow-service:9dc073e86c085809b536da78481276a2ee8dd041
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
        envFrom:
        - configMapRef:
            name: library-config
        env:
        - name: PORT
          value: "3003"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: library-secrets
              key: JWT_SECRET
        - name: MONGODB_URI
          value: "mongodb+srv://f1admin:DGoSkGXpThvjkv2E@cluster0.gsu8i5s.mongodb.net/library-borrow-db?retryWrites=true&w=majority&appName=Cluster0"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          tcpSocket:
            port: 3003
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3003
          initialDelaySeconds: 20
          periodSeconds: 30




