apiVersion: v1
kind: Service
metadata:
  name: borrow-service
  namespace: library-system
  labels:
    app: borrow-service
    component: borrowing
spec:
  type: ClusterIP
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
  selector:
    app: borrow-service
