apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: library-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/SachinthaDaham/Library-Manager-Microservices.git'
    targetRevision: HEAD
    path: 'k8s/ingress'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: library-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
