name: Production AKS CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Authenticate GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish Microservices to GHCR
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          services=("api-gateway" "auth-service" "book-service" "borrow-service" "fine-service" "notification-service" "reservation-service" "frontend")
          for service in "${services[@]}"; do
            echo "========== Building $service =========="
            IMAGE_NAME="ghcr.io/$REPO/$service"
            docker build -t $IMAGE_NAME:${{ github.sha }} ./$service
            docker push $IMAGE_NAME:${{ github.sha }}
            
            # Inject the exact immutable image digest into the K8s manifest
            sed -i "s|image: .*$service:.*|image: $IMAGE_NAME:${{ github.sha }}|g" k8s/$service.yaml
          done

      - name: Authenticate Azure natively via OIDC
        uses: azure/login@v2
        with:
          client-id: "83bc1a9b-447d-8621-8281-62bf5f587001"
          tenant-id: "74531549-6369-4ddc-87a4-32aa878ebbdc"
          subscription-id: "435e28dc-213d-46d4-b1db-d2c10cde033a"

      - name: Connect to Azure Kubernetes Service
        uses: azure/aks-set-context@v3
        with:
          cluster-name: library-aks
          resource-group: Library-reg
          admin: 'true'

      - name: Execute Zero-Downtime Deployment
        run: |
          echo "Applying architectural manifests to AKS cluster..."
          kubectl apply -f k8s/
          echo "Deployment successful."
